repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: mixed-line-ending
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 3b3f7c3f57fe9925356faf5fe6230835138be230 # frozen: v0.15.17
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: https://github.com/codespell-project/codespell
    rev: 2ccb47ff45ad361a21071a7eedda4c37e6ae8c5a # frozen: v2.4.2
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
        args: [--write-changes]
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: f805888065fdb6162e1f800e50bb9460cbd223d6 # frozen: 0.37.2
    hooks:
      - id: check-readthedocs
      - id: check-renovate
  - repo: https://github.com/google/yamlfmt
    rev: 21ca5323a9c87ee37a434e0ca908efc0a89daa07 # frozen: v0.21.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/rhysd/actionlint
    rev: 914e7df21a07ef503a81201c76d2b11c789d3fca # frozen: v1.7.12
    hooks:
      - id: actionlint
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: 3a8ef795727fa946dfcb21c5d07b1442c2362c09 # frozen: v2.23.0
    hooks:
      - id: pyproject-fmt
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: 996abf60411a8d954288ac9856aae7602b80cbda # frozen: v0.22.1
    hooks:
      - id: markdownlint-cli2
        args: [--fix]
        exclude: CHANGELOG\.md
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: 9257c6050c0261b8c57e712f632dc4a8010109a9 # frozen: v1.25.2
    hooks:
      - id: zizmor
