repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: mixed-line-ending
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 2eeb5678de71a00c0902cbda7105d328432f72cb # frozen: v0.16.8
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: https://github.com/codespell-project/codespell
    rev: 57b21406f092110c18776e39b0bda50d37c945c8 # frozen: v2.4.3
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
        args: [--write-changes]
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: c4654a7e007c9619a5eb63c39a456572a0fa1851 # frozen: 0.38.0
    hooks:
      - id: check-readthedocs
      - id: check-renovate
  - repo: https://github.com/google/yamlfmt
    rev: b5ca1890231d5e1e5181fef75a1be609d1e25029 # frozen: v0.21.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/rhysd/actionlint
    rev: 914e7df21a07ef503a81201c76d2b11c789d3fca # frozen: v1.7.12
    hooks:
      - id: actionlint
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: 59e7b26529dc6f15c43063064b8b06ded60d0910 # frozen: v2.29.4
    hooks:
      - id: pyproject-fmt
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: 916ad0aaa108c64d294101002066f530ea170b10 # frozen: v0.23.3
    hooks:
      - id: markdownlint-cli2
        args: [--fix]
        exclude: CHANGELOG\.md
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: fa412071e4f5d44d44f9e365f4676f9df92456a2 # frozen: v1.30.1
    hooks:
      - id: zizmor
