name: Run mypy

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version-file: pyproject.toml

      - name: Install hatch
        run: pip install hatch --upgrade

      - name: Set up reviewdog
        if: github.event_name == 'pull_request'
        uses: reviewdog/action-setup@3f401fe1d58fe77e10d665ab713057375e39b887 # v1.3.0

      - name: Run mypy
        if: github.event_name != 'pull_request'
        run: hatch run mypy geometer

      - name: Run mypy with reviewdog
        if: github.event_name == 'pull_request'
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: hatch run mypy geometer | reviewdog -f=mypy -name=mypy -tee -reporter=github-pr-check -filter-mode nofilter
